name: iSpawner
main: net.drgnome.ispawner.DerpPlugin
version: 1.0.2
author: Siguza
commands:
    edit:
        description: iSpawner
        permissions: ispawner.use
        usage: /edit
permissions:
    ispawner.use:
        default: op
        description: There is just one permission for iSpawner